#!/bin/bash
# =============================================================================
# TRADING FORGE — ONE-COMMAND DEPLOYMENT
#
# Usage:
#   sudo ./deploy.sh              # First-time setup + start
#   sudo ./deploy.sh --restart    # Rebuild and restart without prompts
#   sudo ./deploy.sh --reset      # Destroy volumes and start fresh (DATA LOSS)
#
# Requirements: Docker, Docker Compose v2, openssl, curl
# =============================================================================

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✅ $*${NC}"; }
warn() { echo -e "${YELLOW}⚠️  $*${NC}"; }
err()  { echo -e "${RED}❌ $*${NC}"; }
info() { echo -e "${BLUE}ℹ️  $*${NC}"; }

echo -e "${BOLD}${BLUE}"
echo "╔══════════════════════════════════════════════╗"
echo "║         Trading Forge — Deploy Script        ║"
echo "╚══════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Parse flags ───────────────────────────────────────────────────────────────
RESTART=false; RESET=false
for arg in "$@"; do
  case $arg in
    --restart) RESTART=true ;;
    --reset)   RESET=true  ;;
  esac
done

# ── Root check ────────────────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  err "Run as root: sudo ./deploy.sh"
  exit 1
fi

# ── Prerequisites ─────────────────────────────────────────────────────────────
echo -e "${YELLOW}📋 Checking prerequisites...${NC}"
for cmd in docker openssl curl; do
  command -v "$cmd" >/dev/null 2>&1 || { err "$cmd not found — install it first"; exit 1; }
done
docker compose version >/dev/null 2>&1 || \
  docker-compose version >/dev/null 2>&1 || { err "Docker Compose v2 not found"; exit 1; }
ok "Prerequisites satisfied"

# ── Create required directories ───────────────────────────────────────────────
mkdir -p database/backups logs nginx/ssl

# ── Generate .env.production if not present ───────────────────────────────────
if [ ! -f .env.production ] || $RESET; then
  echo ""
  echo -e "${YELLOW}🔐 Setting up environment...${NC}"

  # Generate strong secrets
  DB_PASS=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
  REDIS_PASS=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
  JWT_SECRET=$(openssl rand -hex 64)

  # Interactive domain prompt (skip if DOMAIN already in env)
  DOMAIN="${DOMAIN:-}"
  if [ -z "$DOMAIN" ]; then
    echo ""
    echo -e "${BOLD}What is your domain name?${NC}"
    echo "  Examples: example.com  /  trade.myapp.com  /  localhost"
    read -rp "Domain [localhost]: " DOMAIN
    DOMAIN="${DOMAIN:-localhost}"
  fi

  # Derive URLs from domain
  if [ "$DOMAIN" = "localhost" ]; then
    FRONTEND_URL="http://localhost:3001"
    BACKEND_URL="http://localhost:8000"
    BACKEND_WS_URL="ws://localhost:8000/market/ws/prices"
    ENVIRONMENT="development"
    DEBUG="true"
  else
    FRONTEND_URL="https://${DOMAIN}"
    BACKEND_URL="https://${DOMAIN}/api"
    BACKEND_WS_URL="wss://${DOMAIN}/market/ws/prices"
    ENVIRONMENT="production"
    DEBUG="false"
  fi

  cat > .env.production << EOF
# =============================================================================
# Trading Forge — Production Environment
# Generated by deploy.sh on $(date)
# KEEP THIS FILE SECRET — never commit to version control.
# =============================================================================

# Database
DB_USER=crypto_admin
DB_PASSWORD=${DB_PASS}
DATABASE_URL=postgresql+asyncpg://crypto_admin:${DB_PASS}@postgres:5432/crypto_platform

# Redis
REDIS_PASSWORD=${REDIS_PASS}
REDIS_URL=redis://:${REDIS_PASS}@redis:6379/0

# JWT / Auth
JWT_SECRET_KEY=${JWT_SECRET}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7

# Application URLs
DOMAIN=${DOMAIN}
FRONTEND_URL=${FRONTEND_URL}
BACKEND_URL=${BACKEND_URL}
BACKEND_WS_URL=${BACKEND_WS_URL}

# CORS — restrict to your domain (add comma-separated extras if needed)
ALLOWED_ORIGINS=${FRONTEND_URL}

# Email (fill in your SMTP provider — leave blank to skip email verification)
SMTP_HOST=smtp.resend.com
SMTP_PORT=587
SMTP_USER=resend
SMTP_PASSWORD=
SMTP_FROM=noreply@${DOMAIN}

# Environment
ENVIRONMENT=${ENVIRONMENT}
DEBUG=${DEBUG}

# Rate Limiting
RATE_LIMIT_SIGNUP=5/hour
RATE_LIMIT_LOGIN=10/15minutes

# Tier Starting Balances (in cents)
TIER_FREE_BALANCE=1000000
TIER_PRO_BALANCE=2500000
TIER_ELITE_BALANCE=10000000
TIER_VALKYRIE_BALANCE=50000000

# Exchange API Keys (optional — leave blank for fallback prices)
KRAKEN_API_KEY=
KRAKEN_API_SECRET=
COINGECKO_API_KEY=
OPENROUTER_API_KEY=

# Stripe Payments (optional — required for paid tiers)
# Get from: https://dashboard.stripe.com/apikeys
STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRICE_ID_PRO=
STRIPE_PRICE_ID_ELITE=
STRIPE_PRICE_ID_VALKYRIE=
EOF

  ok ".env.production created (domain: ${DOMAIN})"
  warn "Edit .env.production to add SMTP_PASSWORD, STRIPE_*, and any API keys before going live"
  echo ""

  if ! $RESTART; then
    read -rp "Continue with deployment? [Y/n]: " CONTINUE
    CONTINUE="${CONTINUE:-Y}"
    [[ "$CONTINUE" =~ ^[Yy] ]] || { info "Aborted. Edit .env.production and re-run."; exit 0; }
  fi
fi

# ── Load environment ───────────────────────────────────────────────────────────
set -a; source .env.production; set +a
DOMAIN="${DOMAIN:-localhost}"
BACKEND_HEALTH="http://localhost:8000/health"
FRONTEND_HEALTH="http://localhost:3001"

# ── Optional: volume reset ────────────────────────────────────────────────────
if $RESET; then
  warn "Destroying all volumes (DATA WILL BE LOST)..."
  docker compose down -v --remove-orphans 2>/dev/null || true
fi

# ── Build and start ───────────────────────────────────────────────────────────
echo -e "${YELLOW}🔨 Building containers...${NC}"
if $RESTART; then
  docker compose build
else
  docker compose build --no-cache
fi

echo -e "${YELLOW}🚀 Starting services...${NC}"
docker compose up -d --remove-orphans
ok "Services started"

# ── Health checks ─────────────────────────────────────────────────────────────
health_check() {
  local name="$1" url="$2"
  local attempts=0 max=24  # up to 2 minutes
  printf "${YELLOW}⏳ Waiting for %s" "$name"
  while [ $attempts -lt $max ]; do
    if curl -fsS "$url" > /dev/null 2>&1; then
      echo -e "${NC}"
      ok "$name is healthy"
      return 0
    fi
    printf "."
    sleep 5
    attempts=$((attempts + 1))
  done
  echo -e "${NC}"
  err "$name failed to become healthy after $((max * 5))s"
  docker compose logs --tail=30 "$name" 2>/dev/null || true
  return 1
}

echo ""
health_check "backend"  "$BACKEND_HEALTH"
health_check "frontend" "$FRONTEND_HEALTH"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  ✅ Deployment complete${NC}"
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════${NC}"
echo ""

if [ "$DOMAIN" = "localhost" ]; then
  echo -e "  ${BLUE}Frontend:${NC}  http://localhost:3001"
  echo -e "  ${BLUE}API:${NC}       http://localhost:8000"
  echo -e "  ${BLUE}API Docs:${NC}  http://localhost:8000/docs"
  echo -e "  ${BLUE}Health:${NC}    http://localhost:8000/health"
else
  echo -e "  ${BLUE}Frontend:${NC}  https://${DOMAIN}"
  echo -e "  ${BLUE}API:${NC}       https://${DOMAIN}/api"
  echo -e "  ${BLUE}Health:${NC}    https://${DOMAIN}/health"
fi

echo ""
echo -e "${YELLOW}📝 Next steps:${NC}"
echo "  1. Verify: curl ${BACKEND_HEALTH}"
echo "  2. Add Stripe webhook URL in Stripe dashboard:"
if [ "$DOMAIN" = "localhost" ]; then
  echo "       Use Stripe CLI: stripe listen --forward-to localhost:8000/payments/webhook"
else
  echo "       https://${DOMAIN}/payments/webhook"
fi
echo "  3. Add email credentials to .env.production (SMTP_PASSWORD)"
echo "  4. Set up SSL: certbot --nginx -d ${DOMAIN}"
echo ""
echo -e "${BLUE}Useful commands:${NC}"
echo "  docker compose logs -f              # stream all logs"
echo "  docker compose logs -f backend      # backend only"
echo "  docker compose ps                   # service status"
echo "  docker compose down                 # stop everything"
echo "  docker compose exec backend bash    # shell into backend"
echo ""
docker compose ps
